const data = {
  products: [
    {
      name: 'Nike Gris shirt',
      slug: 'nike-gris-shirt',
      cotegory: 'Shirts',
      image: 'images/p1.jpg',
      price: '$20',
      brand: 'Nike',
      rating: '4.5',
      numReviews: '10',
      countInStock: '6',
      description: 'high quality shirt',
    },
    {
      name: 'Nike Cyan shirt',
      slug: 'nike-cyan-shirt',
      cotegory: 'Shirts',
      image: 'images/p2.jpg',
      price: '$27',
      brand: 'Nike',
      rating: '7.5',
      numReviews: '5',
      countInStock: '6',
      description: 'high quality shirt',
    },
    {
      name: 'Nike Dark shirt',
      slug: 'nike-dark-shirt',
      cotegory: 'Shirts',
      image: 'images/p3.jpg',
      price: '$50',
      brand: 'Nike',
      rating: '8.5',
      numReviews: '7',
      countInStock: '20',
      description: 'high quality shirt',
    },
    {
      name: 'Nike Bleu shirt',
      slug: 'nike-bleu-shirt',
      cotegory: 'Shirts',
      image: 'images/p4.jpg',
      price: '$30',
      brand: 'Nike',
      rating: '6',
      numReviews: '8',
      countInStock: '13',
      description: 'high quality shirt',
    },
  ],
}
export default data
